### ISSUE TITLE
WHO source doesn't seem to be collecting monkeypox data anymore, and a map of the new outbreak is hard to come by.

### ISSUE THREAD

**Issue by NunoSempere** [owid/monkeypox#12]
The source linked to in https://ourworldindata.org/mpox is https://extranet.who.int/publicemergency/

However, if you click on the "layers" button, the following appears:

In particular, see:

![Screenshot_2024-08-24_08-11-46](https://github.com/user-attachments/assets/fcdb2a75-372a-4264-afe2-3cddd39133c9)

> We are no longer showing monkeypox data in the emergency dashboard. For data related to monkeypox please use the [global trends report](https://worldhealthorg.shinyapps.io/mpx_global/)

Perhaps as a result, some of the charts on https://ourworldindata.org/mpox cut off.

However, the linked [global health report](https://worldhealthorg.shinyapps.io/mpx_global) seems to be updated monthly.

I would love to see up to date monkeypox graphs, some collaboration with the WHO to make daily data accessible, as this gives a better sense of where we are on the exponential. I don't think I need to make the case that better presented information leads to better decisions to OWID though :)

**Comment by spoonerf** [comment]
Hi @NunoSempere 

Thanks for getting in touch and highlighting this to us. The source noted in our explorer was out of date, we now use [this WHO data source](https://frontdoor-l4uikgap6gz3m.azurefd.net/MPX/V_MPX_VALIDATED_DAILY) for confirmed cases and deaths. This is also updated monthly and has the same values as the [global health report](https://worldhealthorg.shinyapps.io/mpx_global/) that you shared. 

I have now updated the explorer to better reflect the data source we use and will update this repo in the coming days to describe our current data pipeline. 

Thanks again,

Fiona

**Comment by NunoSempere** [comment]
Hey Fiona,

What do you think about trying to find or creating a source that updates faster than monthly? For a disease that is rapidly developing, it seems like this is a pretty slow speed.

Best,
Nuño

**Comment by spoonerf** [comment]
Hi Nuño, 

Yes that is something that is important for us. We have recently started including data from [Africa CDC](https://africacdc.org/download/africa-cdc-weekly-event-based-surveillance-report-august-2024/) on suspected cases, which you'll see in the default view of the explorer. This dataset is updated weekly, but the quality is somewhat variable, so we are only using this for suspected cases as this isn't currently provided by our main data source, the WHO. 

We are also speaking with [Global.health](https://global.health/), who are working to pull together a detailed dataset that will be updated more frequently; I expect this will be made public in the next week. 

It is also likely that the WHO will increase the cadence of their updates in response to the current situation. We still believe that the WHO is the best source confirmed cases and deaths so we will continue to use this but monitor the situation closely.
