### ISSUE TITLE
Stopped data updates?

### ISSUE THREAD

**Issue by als329** [owid/monkeypox#3]
Hello! Is OWID no longer updating MPX case counts? Last date with data is 11/10

**Comment by edomt** [comment]
Hi @als329 

We haven't been able to fetch new data from the WHO API since 11 November. We are still figuring this out but we have got in touch with them about this, and hope that we will have the most up-to-date data soon.

**Comment by pearcircuitmike** [comment]
Any update on this issue? Thanks.

**Comment by edomt** [comment]
Hi @pearcircuitmike 

The WHO have given us the link to their new API, so updates have now resumed.
